[phases.setup]
nixPkgs = ["python313", "python313Packages.pip"]

[phases.install]
cmds = [
	"python -m ensurepip --upgrade",
	"python -m pip install --upgrade pip",
	"python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Skipping build phase' "]

[start]
cmd = "python -m uvicorn swarmz_runtime.api.server:app --host 0.0.0.0 --port ${PORT:-8000}"
